project:
  output-dir: docs
  type: book

book:
  title: "CASA0023 Learning Diary"
  author: "Wing Ka Ho"
  navbar:
    logo: "images/casa_logo.png"
    collapse: true
    collapse-below: lg
    background: light
    reader-mode: true
    search: true
    right:
      - icon: github
  sidebar:
    title: "CASA0023 Remotely Sensing Cities and Environments"
    style: docked
    reader-mode: true
  repo-url: https://github.com/WinkiH/CASA0023_LearningDiary
  repo-actions: [issue]
  google-analytics:
    tracking-id: "G-5LZK055F2X"
    anonymize-ip: true
  date: "3/14/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week5.qmd
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
        light: [cosmo, flatly]
        dark: [cosmo, darkly]
    code-link: true
      
  pdf:
    documentclass: scrreprt

editor: visual

